### ISSUE TITLE
Decide on number of hours needed/desired for funding

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/geotargets-isc-proposal#7]
For [`volcalc`](https://github.com/Meredith-Lab/volcalc) we asked for a total of 260 hours and we've actually spent about 120 hours on it so far (probably more, but that was what time we logged in our group time tracker thing).  That 120 hours included a significant re-factor, new features, documentation, and prepping for CRAN, so probably on-par for an initial release of something like `geotargets`.  I suggest maybe rounding up to a total of maybe 200 hours to also include JOSS and rOpenSci submission.

The current timeline is 9 months total (starting in March) which I think works out to an average of 5.5 hours per week total (2.25 hours per person, if we were to contribute equally).  Does that sound like a good level of commitment, @njtierney?

(also tagging @KristinaRiemer to double-check that this is an OK amount of my time to spend on this project)

**Comment by njtierney** [comment]
Thanks so much for working that out - I find it hard to cost/estimate my time on projects!

I think that sounds like a good level of commitment to me - but what if we round it up to 6 hours per week so then its 3 hours each? So something like 220 hours? Or 4 hours per week (2 each?) if we want less?

I think having a little more wiggle room would be good, especially since there is a pretty large number of geospatial features we could end up using. I'm also happy to go with fewer hours and we can maybe apply for another round of funding in the future?

**Comment by Aariq** [comment]
That sounds good to me.  6 hrs/week * 9 months * 4 weeks/month = 216 hours.
